language: node_js
node_js:
  - 14.17.6
script:
  - "npm run build"
  - "npm run test:nowatch"

# Config to deploy our app to Heroku (you must generate token from Heroku CLI and copy paste it to Travis website)
# 'adinh-book-demo-store-web' is the name of th app defined on Heroku website
deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU_TOKEN
  app: "adinh-book-demo-store-web"
  skip_cleanup: true
  on:
    all_branches: true